/**
 * Main-thread `sandkit.api` namespaces.
 *
 * This is the public mod API on the main thread. Prefer these methods over
 * {@link sandkit.engine} when both exist.
 */

export * from "./action"
export * from "./assets"
export * from "./authorization"
export * from "./building"
export * from "./camera"
export * from "./constants"
export * from "./cooldown"
export * from "./discoveries"
export * from "./effects"
export * from "./elements"
export * from "./energy"
export * from "./events"
export * from "./excavation"
export * from "./gameconfig"
export * from "./grid"
export * from "./i18n"
export * from "./input"
export * from "./items"
export * from "./lights"
export * from "./maps"
export * from "./mods"
export * from "./player"
export * from "./processing"
export * from "./progression"
export * from "./projectiles"
export * from "./raycast"
export * from "./reactions"
export * from "./rendering"
export * from "./resources"
export * from "./scene"
export * from "./schedule"
export * from "./settings"
export * from "./shared"
export * from "./signals"
export * from "./sound"
export * from "./sprites"
export * from "./storage"
export * from "./structureBehaviors"
export * from "./structures"
export * from "./tech"
export * from "./terrains"
export * from "./time"
export * from "./tools"
export * from "./triggers"
export * from "./ui"
export * from "./upgrades"
export * from "./workers"
export * from "./world"

export type { SandkitApi } from "./sandkit-api"

// Shared namespaces also present on sandkit.api
export * from "../../shared/api/collector"
export * from "../../shared/api/fire"
export * from "../../shared/api/hooks"
export * from "../../shared/api/patterns"
export * from "../../shared/api/random"
export * from "../../shared/api/utils"
